"""empty message

Revision ID: 01b18ea82379
Revises: c350565879df
Create Date: 2023-01-29 16:43:48.336308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01b18ea82379'
down_revision = 'c350565879df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_order_id', sa.Integer(), nullable=True),
    sa.Column('fk_tax_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['fk_tax_id'], ['tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_invoice_id', sa.Integer(), nullable=True),
    sa.Column('fk_tax_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['fk_tax_id'], ['tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_invoice_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('pay_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('pay_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('pay_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bank_account', ['fk_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'invoice', ['fk_invoice_id'], ['id'])
        batch_op.create_foreign_key(None, 'company', ['fk_company_id'], ['id'])
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_client_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('quotation_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['fk_client_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_warehouse_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('stock_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('stock_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['fk_item_id'], ['id'])
        batch_op.create_foreign_key(None, 'warehouse', ['fk_warehouse_id'], ['id'])
        batch_op.drop_column('warehouse_id')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('subscription_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('subscription_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['fk_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'company', ['fk_company_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('tax_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['fk_user_id'], ['id'])
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tax_ibfk_1', 'company', ['company_id'], ['id'])
        batch_op.drop_column('fk_user_id')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscription_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('subscription_ibfk_1', 'company', ['company_id'], ['id'])
        batch_op.drop_column('fk_user_id')
        batch_op.drop_column('fk_company_id')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('warehouse_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stock_ibfk_3', 'warehouse', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key('stock_ibfk_2', 'item', ['item_id'], ['id'])
        batch_op.drop_column('fk_warehouse_id')
        batch_op.drop_column('fk_item_id')

    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quotation_ibfk_1', 'client', ['client_id'], ['id'])
        batch_op.drop_column('fk_client_id')

    with op.batch_alter_table('pay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pay_ibfk_4', 'invoice', ['invoice_id'], ['id'])
        batch_op.create_foreign_key('pay_ibfk_2', 'company', ['company_id'], ['id'])
        batch_op.create_foreign_key('pay_ibfk_1', 'bank_account', ['account_id'], ['id'])
        batch_op.drop_column('fk_invoice_id')
        batch_op.drop_column('fk_account_id')
        batch_op.drop_column('fk_company_id')

    op.drop_table('invoice_tax')
    op.drop_table('order_tax')
    # ### end Alembic commands ###
