"""empty message

Revision ID: 1331e513b1b8
Revises: c5b300b9f838
Create Date: 2023-01-30 14:00:31.717511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1331e513b1b8'
down_revision = 'c5b300b9f838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'warehouse', ['fk_warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_2', 'store', ['fk_warehouse_id'], ['id'])

    # ### end Alembic commands ###
