"""empty message

Revision ID: 1edbd902bdfc
Revises: 01b18ea82379
Create Date: 2023-01-29 18:53:36.022535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1edbd902bdfc'
down_revision = '01b18ea82379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.drop_column('for_sell')
        batch_op.drop_column('for_buy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_buy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('for_sell', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
