"""empty message

Revision ID: 75fbd76158c5
Revises: c2b9c80d5bbe
Create Date: 2023-01-29 22:27:06.840996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75fbd76158c5'
down_revision = 'c2b9c80d5bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=10), nullable=True),
    sa.Column('fk_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_store_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'store', ['fk_warehouse_id'], ['id'])
        batch_op.create_foreign_key(None, 'store', ['fk_store_id'], ['id'])

    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_constraint('warehouse_ibfk_2', type_='foreignkey')
        batch_op.drop_column('fk_employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('warehouse_ibfk_2', 'user', ['fk_employee_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_warehouse_id')
        batch_op.drop_column('fk_store_id')

    op.drop_table('store')
    # ### end Alembic commands ###
