"""empty message

Revision ID: c2b9c80d5bbe
Revises: d6793e67664d
Create Date: 2023-01-29 22:08:25.436472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2b9c80d5bbe'
down_revision = 'd6793e67664d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fk_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_employee_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('warehouse_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('warehouse_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('warehouse_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['fk_company_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['fk_employee_id'], ['id'])
        batch_op.drop_column('contact_id')
        batch_op.drop_column('address_id')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('warehouse_ibfk_1', 'address', ['address_id'], ['id'])
        batch_op.create_foreign_key('warehouse_ibfk_3', 'contact', ['contact_id'], ['id'])
        batch_op.create_foreign_key('warehouse_ibfk_2', 'company', ['company_id'], ['id'])
        batch_op.drop_column('fk_employee_id')
        batch_op.drop_column('fk_company_id')
        batch_op.drop_column('contact')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
