"""empty message

Revision ID: c350565879df
Revises: df10dfa0adc1
Create Date: 2023-01-26 13:28:43.446925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c350565879df'
down_revision = 'df10dfa0adc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint('company_ibfk_1', type_='foreignkey')
        batch_op.drop_column('manager')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_ibfk_1', 'user', ['created_by'], ['id'])

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('company_ibfk_1', 'user', ['manager'], ['id'])

    # ### end Alembic commands ###
