"""empty message

Revision ID: d6793e67664d
Revises: 1edbd902bdfc
Create Date: 2023-01-29 19:19:43.933689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6793e67664d'
down_revision = '1edbd902bdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.drop_column('on_applied_TVA')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_applied_TVA', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
